# Generated by Django 4.2.2 on 2024-07-26 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('title', models.CharField(max_length=300)),
                ('date_added', models.DateTimeField()),
                ('purchase_cost', models.IntegerField(default=0)),
                ('selling_cost', models.IntegerField(default=0)),
                ('profit', models.IntegerField(default=0)),
                ('amazon_link', models.URLField()),
                ('ebay_link', models.URLField()),
                ('country', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('age_range', models.CharField(max_length=100)),
                ('audiance', models.CharField(max_length=100)),
                ('intrests', models.CharField(blank=True, max_length=100, null=True)),
                ('approximate_CPA', models.CharField(max_length=100)),
                ('saturation', models.CharField(max_length=100)),
                ('fb_ads', models.URLField()),
                ('videos', models.URLField()),
                ('stores_selling_it', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('fee_paid', models.BooleanField(default=False)),
                ('joining_date', models.DateTimeField()),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('user_subscription_record', models.BooleanField(default=False)),
            ],
        ),
    ]
