# Generated by Django 4.2.2 on 2024-07-28 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_niche_products_niche_profile_niche'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service_Offer_Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('service', models.CharField(max_length=20)),
                ('message', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
