# Generated by Django 4.2.2 on 2024-07-29 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_service_offer_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='niche',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.niche'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='niche',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.niche'),
        ),
    ]
