# Generated by Django 4.2.2 on 2024-07-31 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_products_niche_alter_profile_niche'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='amazon_link',
        ),
        migrations.RemoveField(
            model_name='products',
            name='ebay_link',
        ),
        migrations.AddField(
            model_name='products',
            name='alibab_link',
            field=models.URLField(default='www.elitedrops.net'),
        ),
        migrations.AddField(
            model_name='products',
            name='aliexpress_link',
            field=models.URLField(default='www.elitedrops.net'),
        ),
        migrations.AlterField(
            model_name='products',
            name='fb_ads',
            field=models.URLField(default='www.elitedrops.net'),
        ),
        migrations.AlterField(
            model_name='products',
            name='stores_selling_it',
            field=models.URLField(default='www.elitedrops.net'),
        ),
        migrations.AlterField(
            model_name='products',
            name='videos',
            field=models.URLField(default='www.elitedrops.net'),
        ),
    ]
