# Generated by Django 4.2.2 on 2024-07-31 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_products_amazon_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='alibab_link',
            field=models.URLField(blank=True, default='www.elitedrops.net', null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='aliexpress_link',
            field=models.URLField(blank=True, default='www.elitedrops.net', null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='fb_ads',
            field=models.URLField(blank=True, default='www.elitedrops.net', null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='stores_selling_it',
            field=models.URLField(blank=True, default='www.elitedrops.net', null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='videos',
            field=models.URLField(blank=True, default='www.elitedrops.net', null=True),
        ),
    ]
