# Generated by Django 4.2.2 on 2024-08-01 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_products_alibab_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='alibab_link',
            field=models.URLField(default='www.elitedrops.net/no_link/'),
        ),
        migrations.AlterField(
            model_name='products',
            name='aliexpress_link',
            field=models.URLField(default='www.elitedrops.net/no_link/'),
        ),
        migrations.AlterField(
            model_name='products',
            name='fb_ads',
            field=models.URLField(default='www.elitedrops.net/no_link/'),
        ),
        migrations.AlterField(
            model_name='products',
            name='stores_selling_it',
            field=models.URLField(default='www.elitedrops.net/no_link/'),
        ),
        migrations.AlterField(
            model_name='products',
            name='videos',
            field=models.URLField(default='www.elitedrops.net/no_link/'),
        ),
    ]
