# Generated by Django 4.2.2 on 2024-08-01 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_products_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='p1',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='p2',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='p3',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
