# Generated by Django 4.2.2 on 2024-08-01 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_profile_p1_profile_p2_profile_p3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='p1',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='p2',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='p3',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
